### ISSUE TITLE
Practica Expresiones Booleanas

### ISSUE THREAD

**Issue by KarenIMont** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-ximena-karen-1as#1]
[Practica_ExpresionesBooleanas.pdf](https://github.com/user-attachments/files/18045511/Practica_ExpresionesBooleanas.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
